backend:
  name: github
  branch: main
  repo: michaelpb/pta

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
local_backend: true # comment to disable local admin
logo_url: "https://peoplestransit.org/images/logos/bus_and_transit_map.svg.png"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bulletin" # Used in the UI, ie.: "New Post"
    folder: "content/en/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "c"
    label: "Custom Page"
    folder: "content/en/c/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Breadcrumbs"
        name: "breadcrumbs"
        widget: "list"
        summary: '{{fields.title}} ({{fields.url}})'
        hint: "Adding one or more 'breadcrumbs' creates a series of links at the top of the page, in order to communicate to users a hierarchical organizational structure."
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
      - label: "Aliases"
        name: "aliases"
        widget: "list"
        hint: "Aliases allow for extra public-facing URL paths that redirect to the canonical URL path (eg the one at /c/). Use this to make more memorable URLs, eg '/jan18rsvp'."
        field: {label: "URL path:", name: "url", widget: "string"}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.caption}} ({{fields.image}})'
        fields:
        - {label: "Image", name: "image", widget: "image", required: true}
        - {label: "Image Description", name: "alt", widget: "string", required: true, hint: "Specify 'alt-attribute' description, to be used by screen-readers."}
        - {label: "Caption", name: "caption", widget: "string", required: false}
        - {label: "URL Link", name: "url", widget: "string", required: false}
      - {label: "Body (After Gallery)", name: "bodyAfterGallery", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/en/_index.html"
        label: "Landing (EN)"
        name: "landing"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/en/about/_index.md"
        label: "About (EN)"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/en/post/_index.md"
        label: "Bulletin (EN)"
        name: "bulletin"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body (left-side)", name: "body", widget: "markdown"}

      - file: "content/en/campaigns/_index.md"
        label: "Campaigns (EN)"
        name: "campaigns"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/en/join/_index.md"
        label: "Join (EN)"
        name: "join"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
