backend:
  name: github
  branch: main
  repo: michaelpb/pta

media_folder: "static/images/uploads"
public_folder: "images/uploads"
publish_mode: editorial_workflow
local_backend: true # comment to disable local admin
logo_url: "https://peoplestransit.org/static/images/logos/bus_and_transit_map.svg.png"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bulletin" # Used in the UI, ie.: "New Post"
    folder: "content/en/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/en/_index.html"
        label: "Landing (EN)"
        name: "landing"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Jumbotron Copy Left (Top)", name: "jumbotron_copy_top", widget: "string"}
          - {label: "Jumbotron Copy Left (Middle)", name: "jumbotron_copy_middle", widget: "string"}
          - {label: "Jumbotron Copy Left (Bottom)", name: "jumbotron_copy_bottom", widget: "string"}
          - {label: "Jumbotron Copy Right", name: "jumbotron_copy_pullquote", widget: "text"}
          - {label: "Jumbotron Call-to-Action Button Text", name: "jumbotron_copy_cta_button", widget: "string"}
          - {label: "Jumbotron Call-to-Action Button URL", name: "jumbotron_cta_button_destination", widget: "string"}
          - {label: "Xtra Column 1", name: "xtra_column_1", widget: "markdown", required: false}
          - {label: "Xtra Column 2", name: "xtra_column_2", widget: "markdown", required: false}
          #- {label: "Body", name: "body", widget: "text"}

      - file: "content/en/about/_index.md"
        label: "About (EN)"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/en/post/_index.md"
        label: "Bulletin (EN)"
        name: "bulletin"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body (left-side)", name: "body", widget: "markdown"}

      - file: "content/en/campaigns/_index.md"
        label: "Campaigns (EN)"
        name: "campaigns"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/en/join/_index.md"
        label: "Join (EN)"
        name: "join"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover Image", name: "featured_image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
