title = "People's Transit Alliance"
baseURL = "https://peoplestransit.netlify.app/"
languageCode = "en-us"
theme = "ananke"
publishdir = "public/"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "People's Transit Alliance"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/logos/route_and_flower.svg.png"
  description = "Free Transit Now!"
  facebook = "https://www.facebook.com/JovankaForThePeople/"
  twitter = "https://twitter.com/JovankaBeckles/"
  instagram = "https://www.instagram.com/jovankabeckles/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-red"
  #featured_video = "/videos/jb_video_reenc.webm"
  recent_posts_number = 2
  custom_css = ["css/pta_custom.css"]
  google_fonts = [
    #["Bebas Neue"],
    #["Rubik", "200, 400, 800"],
    #["Titillium Web", "200, 400, 700, 900"],
    ["Teko", "300, 400, 700"],
    ["Montserrat", "200, 400, 800"],
    ["Lora", "400, 700"],
  ]


#[menu]
#
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10
#
#  [[menu.main]]
#    identifier = "policy"
#    name = "Policy"
#    url = "/policy/"
#    weight = 20
#
#  [[menu.main]]
#    identifier = "bulletin"
#    name = "Bulletin"
#    url = "/post/"
#    weight = 30
#
#  [[menu.main]]
#    identifier = "join"
#    name = "Join"
#    url = "/join/"
#    weight = 40
#    [menu.main.params]
#      asButton = true
#


