title = "People's Transit Alliance"
baseURL = "https://michaelpb.github.io/pta/"
languageCode = "en-us"
theme = "ananke"
publishdir = "docs/"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "People's Transit Alliance"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "images/logo_draft.jpeg"
  description = "Free Transit Now!"
  facebook = ""
  twitter = "https://twitter.com/PeoplesTransitAlliance"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-red"
  featured_video = "/videos/jb_video_reenc.webm"
  recent_posts_number = 2
  custom_css = ["css/pta_custom.css"]

  google_fonts = [
    ["Bebas Neue"],
    ["Montserrat", "200, 400, 800"],
  ]
